name: custom_widget
description: A widget that makes it easy to have a custom painted and animated widget in Flutter
version: 0.1.0
author: Adam Fuller
homepage: https://github.com/adamfuller/custom_widget

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
